### PR TITLE
Update Accord.Video.FFMPEG (Lets try this again..)

### PR DESCRIPTION
**Pull request by MelvinGr**

### CODE REVIEW

**Comment by MelvinGr** [comment]
> /home/travis/build/accord-net/framework/Sources/Accord.MachineLearning/Accord.MachineLearning.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->
	VectorMachines/Learning/LinearNewtonMethod.cs(293,17): error CS0649: Warning as Error: Field `Accord.MachineLearning.VectorMachines.Learning.BaseLinearNewtonMethod<TModel,TKernel,TInput>.kernel' is never assigned to, and will always have its default value
	 10 Warning(s)
	 1 Error(s)
Time Elapsed 00:00:06.4210770
make: *** [build] Error 1

Failure (in Accord.MachineLearning.csproj) has nothing to do with my code

**Comment by cesarsouza** [comment]
Hi Melvin,

Wow, thank you very much for this pull request! I am still going through it, but just to confirm what I am seeing, have you updated FFMPEG to the latest version, rewriting the code to use the new FFMPEG interfaces that had been introduced since 2010, while also updating it to use more modern C++ features? I've been trying since forever to find enough time to do all of this, but never managed to do it because I've always had other priorities in the list. Thank you so much! I am sure many people will find it _extremely_ useful! 

I will integrate it as soon as I can. Also, have you tested it outside of the currently provided unit tests, such as for example in the video-related sample applications?

Regards,
Cesar

**Comment by cesarsouza** [comment]
Hi Melvin,

I am trying to get the code you committed working. However, I get FileNotFoundException's when trying to load the Accord.Video.FFMPEG.dll it has generated.

Before the project was using .dll' files generated from FFMPEG during runtime, but I see that in your branch you have removed the ffmpeg/bin folder and there are no .dll's committed in the External/ffmpeg folder. Please, may I ask if this is the intended scenario, or did the .dll's get missing at some point?

Best regards,
Cesar

**Comment by MelvinGr** [comment]
You could check if you are compiling for the correct architecture (win32,
x64), the any cpu mode might not work as the project uses native c++ and
should check for the correct dll load time (check the example).

Kind regards

2017-01-25 22:43 GMT+01:00 César Souza <notifications@github.com>:

**Comment by cesarsouza** [comment]
Thanks! When you say check for the correct .dll, do you mean that the .dll's should have been available in the unit test project you included as an example? 

In this case I am downloading the .dlls from the "shared" distribution in Zeranoe's website. 

I managed to get it working with WMV and MPEG2 videos. However, I can't seem to get it working with mp4 (H264) or even mkv containers (as in your original demo)  :-(

Regards,
Cesar

**Comment by cesarsouza** [comment]
I get a "-22" error code in the "avcodec_open2(codecContext, codec, nullptr)" line of VideoFileWriter.cpp.

**Comment by cesarsouza** [comment]
Hi there,

The problem was actually the pixel format being passed to H264. I was getting error -22 (Invalid parameter) because, at least in my computer, libx264 doesn't seem to like AV_PIX_FMT_YUVJ444P. It works with AV_PIX_FMT_YUVJ420P though!

Thanks for the help and thanks again for the contribution!

Regards,
Cesar

**Comment by cesarsouza** [comment]
This pull request has been merged already, but for some reason it was not marked as merge here in GitHub, so I am closing it manually (again thanks a lot for the contribution!)

**Comment by janagam** [comment]
hi..can u provide sample example to read the video or write to vide

**Pull request closed without merging**
