### PR TITLE
Fixing HighBoost

### PR DESCRIPTION
**Pull request by hzawary**

### CODE REVIEW

**Comment by cesarsouza** [comment]
Hi @hzawary!

Thanks a lot for the contribution!! Before I can accept it, can you please sign the CLA above? 

Thanks!!
Cesar

**Comment by hzawary** [comment]
Hi @cesarsouza :)

It's done!

Best,
HZ

**Comment by justingruenberg** [comment]
This merge breaks the build.  

https://github.com/accord-net/framework/blob/5a4993ddc833be8b87101bb221da1750e9b0f304/Sources/Accord.Imaging/Filters/HighBoost.cs#L76

Kernel is not accessible from here.  Either replace this line with `createFilter()` or make kernel protected in the Convolution class.

**Comment by fdncred** [comment]
I'll accept a PR to fix this.

**Comment by justingruenberg** [comment]
See #1809.  Please wait until the CI gets to try it, since I just made the change in the web ui and haven't tested it locally.

**Pull request merged**
