### PR TITLE
Random Forest

### PR DESCRIPTION
**Pull request by mthmn20**
Implementation of Random Forest for Accord.NET. Currently only supports binary classification.

### CODE REVIEW

**Comment by mthmn20** [comment]
Hey @cesarsouza, I noticed you accepted a bunch of pull requests recently but haven't gotten to this one . Is there anything else you'd like me to do before it's ready to be merged in?

**Comment by jbruening** [comment]
@mthmn20 The full file changes due to EOL in 4266de3 and 35886e8 might be preventing you from getting this pulled.

**Comment by mthmn20** [comment]
Oh, sorry for that! Here are links that show those changes without the whitespace issue so you can see the actual changes:
https://github.com/accord-net/framework/commit/4266de3529c460a28fffa2340d23f38f193ba16d?diff=split&w=1
https://github.com/accord-net/framework/commit/35886e8faa8989f4aa9176459aa9ab30aa882db3?diff=split&w=1

**Comment by cesarsouza** [comment]
Hi @mthmn20 ! First of all, thank you very much for the contribution!

The reason that I wasn't able to review and accept the request before is because I had to go on other things due the AForge.NET merge/reorganization before accepting further pull requests. I will download your pull request to a separate branch and try to solve the new conflicts (such as the one that @jbruening cited - thanks for noticing!) 

I will also try to take care of any necessary changes to make it fit with the rest of the framework.

Thank you again for the contribution!

Best regards,
Cesar

**Comment by mthmn20** [comment]
Awesome @cesarsouza, thanks!

**Comment by cesarsouza** [comment]
Thanks a lot for the contribution! I have integrated the source code, but had to perform some API changes to make it consistent with the rest of the framework.

**Pull request merged**
