### PR TITLE
GH-1075 Add custom QLearning implementation for Animat and add Unity Animat sample

### PR DESCRIPTION
**Pull request by FireDragonGameStudio**
Hy @cesarsouza ,
as stated in #1075 I added my version of QLearning to Animat and also added a Unity sample, where I reimplemented Animat. The custom QLearning version was implemented like this tutorial -> [http://mnemstudio.org/path-finding-q-learning-tutorial.htm](http://mnemstudio.org/path-finding-q-learning-tutorial.htm)

Best regards :)

### CODE REVIEW

**Comment by cesarsouza** [comment]
Amazing @FireDragonGameStudio! Thanks a lot for the PR!

**Comment by cesarsouza** [comment]
Hi @FireDragonGameStudio, 

Ok, now I see why your implementation seems to always work better - the point is that this implementation is using each different position in the map as a different state in the model. This is different from what the original application was trying to achieve, which was to be able to navigate a robot based only on its "sensors", and it's also way easier to solve. 

I guess that it could have been possible to use the original QLearning class to solve this problem as well, all that would be needed would be to update the reward and state functions considering this "global" view of the problem instead. I will see if I can take a look on it.

Thanks!

Regards,
Cesar

**Comment by FireDragonGameStudio** [comment]
Hy @cesarsouza,
thank you for your explanation. :) After having a closer look at the changes, I see what you mean. I think I was to distracted by the tutorial (and its different approach), to realize the obvious possibility to solve it with the existing QLearning class. 

After playing around with Animat sample today, I noticed that sample2 can also be solved with the default implementation, when the rates for learning and the exploration are changed to 0.1 and 0.2. It takes a few attempts, but works.

PS: Do you want me to adapt the Unity sample, to match the implemntation of the WinForms application?

Best regards :)

qlearning_params_opt

**Comment by cesarsouza** [comment]
Hi @FireDragonGameStudio, 

I think your implementation is interesting and could still be offered as an alternative in the Unity sample. I just decided to modify the WinForms version because I thought it might be confusing to demonstrate a class that is not contained in the main framework, and I unfortunately I haven't got much time available to work into integrating it 100% right now.

I haven't actually seen the Unity sample yet because I don't have enough space to re-install Unity in my Surface right now (super small SSD), but I suppose that people looking to apply Q-Learning in Unity might want to address a scenario similar to the one you have addressed. So I think it may be fine to keep it as it is, unless you would really like to update it :-)

Regards,
Cesar

**Comment by FireDragonGameStudio** [comment]
Hy @cesarsouza,
ok, let's keep it like it is for now, as it is nearly identical. ^^ I'll play around with some more algorithms, elaborate possibilities/use cases and open a new issue, when I'm finished with a new Unity example. :)

Best regards :)

**Pull request merged**
