### PR TITLE
Bug in Kernels

### PR DESCRIPTION
**Pull request by NikolasMarkou**
Gaussian Distribution is -e^(-x^2/2)*x * constant
since x is assumed to be always squared the correct
derivative is -e^(x*0.5)*Math.Sqrt(x) * constant,

### CODE REVIEW

**Comment by cesarsouza** [comment]
Hi Nikolas!

Thank you very much for the pull request! I still need to go through the original paper to recheck and recover exactly what was expected from that particular function, but it definitely seems like something was wrong there. However, wouldn't the derivative of the Gaussian profile function be ``` -0.5 * Profile(x)``` instead?

Best regards,
Cesar

**Comment by NikolasMarkou** [comment]
Hello Cesar,
the profile is Math.Exp(-0.5 * x) which translates (due to the square euclidean thing you do to save calculations) to e^(-x^2/2) and thus in the previous version made the derivative equal to -x^2 * e^(-x^2/2), This is however wrong  as it should -x/2 * e^(-x^2/2) , i assumed you didnt care about the constant and dropped it like you dropped the 1/(2*pi)^0.5 constant.
I dont see how the derivative should be -x * Profile(x). Do you demand something like that from the base class? i may have missed that

**Comment by cesarsouza** [comment]
Hi Nikolas,

I got some time to look more carefully into this issue. The framework was supposed to be using the definitions given in:
https://courses.csail.mit.edu/6.869/handouts/PAMIMeanshift.pdf and http://www.serc.iisc.ernet.in/~venky/SE263/slides/Mean-Shift-Theory.pdf

In the first paper, the Gaussian kernel profile is being defined in equation 9 as ```exp(0.5 * x)``` (without squares). As such, it's derivative should have been ```-0.5 * exp(0.5 * x)```. I agree that the current framework implementation (as of version 2.14) is wrong, but I think the correction should be to set the profile as ```-0.5 * exp(0.5 * x)``` rather than ``` -e^(x0.5)*Math.Sqrt(x) * constant```. I will also check the other usages in MeanShift to see if they all agree with those definitions.

PS: As you correctly guessed, yes the framework is dropping many constants because they are not needed by the Mean-Shift algorithm. Mean-Shift normalizes the kernel profile derivatives, so any common multiplicative constants would have been normalized at the end. Are you trying to use the kernel profiles and derivatives for something else than Mean-Shift? In this case I agree that it could be better to offer also the complete implementation with the constants as you initially suggested.

Best regards,
Cesar

**Comment by NikolasMarkou** [comment]
Oh, I just saw the paper. Yes you are correct on that. 
I went with original definition of the normal distribution and its derivative.
Here it says that *While these two kernels will suffice for most applications
we are interested in,all the results presented below are valid
for arbitrary kernels within the conditions to be stated.* so i'm guessing it still works.
I had issues with deciding on the bandwidth on mean shift and i kept getting different results if I shuffled the same data.
I made some changes that go a bit off the original paper of mean shift and give stable results

https://github.com/NikolasMarkou/framework/commit/2e50438af7377944d3eb6484c8152aac92f02a0e
https://github.com/NikolasMarkou/framework/commit/18771f1e7d08cceba61236ab4b881bfde3d6dc2c

**Comment by cesarsouza** [comment]
Hi Nikolas, 

Many thanks for the updates! I have merged it, but I will need to make a few adjustments in the code... Do you have an example of a database that was causing you problems, so I can write a few unit tests based on it?

**Comment by cesarsouza** [comment]
By the way, I am better reviewing the code, and I noticed that you removed the seeding strategy... Was there any reason for it?

**Comment by cesarsouza** [comment]
I've merged the pull request to the branch GH-68. In the meantime, I added some corrections on the profiles and their derivatives to the main branch. Can you please provide some test data that I can use to encounter the same issues you were facing? Thanks!

**Comment by NikolasMarkou** [comment]
Hello Cesar, I'll try and make you a sample of what I used in the mean shift to demonstate the fix.

**Comment by NikolasMarkou** [comment]
The seeding strategy created modes in positions there were none and when deciding at the end which seeds to keep I noticed that the order of the input points changed the output. Since I was running parallized tasks to gather my points (always the same points ) I was keep getting different modes at the end of each run (with the same settings).
As I said I'll try to make a sample code to demonstrate the fix.

**Pull request merged**
