### PR TITLE
Updated Accord.Video.FFMPEG.GPL

### PR DESCRIPTION
**Pull request by MelvinGr**
I have updated the Accord.Video.FFMPEG.GPL code to work with the latest ffmpeg source. I've, also added an example.

### CODE REVIEW

**Comment by heldersepu** [comment]
Would love to see this merged into the project, but there seem to be some failed checks :(

**Comment by MelvinGr** [comment]
The build error was not related to my code, but it is fixed. 
"VectorMachines/Learning/LinearNewtonMethod.cs(293,17): error CS0649: Warning as Error: Field"  

However the 'Accord.Tests.MachineLearning.*' tests failing is not because of me?

**Comment by ChenZhaobin** [comment]
@Melvin  why it's no difference when I pull from nuget? still version 3.3.0? And the bug still exists when I call in web api?Very appreciate for your work,thanks!

**Comment by MelvinGr** [comment]
@ChenZhaobin The code had not been merged yet

**Comment by ChenZhaobin** [comment]
Expecting!Thanks for warmly reply

**Comment by ChenZhaobin** [comment]
Hi,@Melvin. Maybe this question below has nothing to do with accord.net.I just want to know where is the problem in my program,I will be appreciate if you give me some suggestion!:
I want to use fmmpeg to convert images to mp4 use command "-f image2  -i    IMG/%d.jpg  -vcodec libx264  -r  15  -s 640x480  -pix_fmt yuv420p  -y result.mp4"
 It is ok when I use origin images extracted from a mp4 video,but when I resize the image using afforge or opencv methods ,then I get some odd exceptions confused me for a long time ,but when I use accord.video.ffmpg,it has no problem except for GPL issue.
the error log is below 
 Found EOI before any SOF, ignoring
[mjpeg @ 01240b80] No JPEG data found in image
    Last message repeated 1 times
[mjpeg @ 01240b80] bits 148 is invalid
[mjpeg @ 01240b80] bits 159 is invalid
[mjpeg @ 01240b80] bits 139 is invalid
[mjpeg @ 01240b80] [IMGUTILS @ 0028f494] Picture size 7456x63479 is invalid
[mjpeg @ 01240b80] No JPEG data found in image
    Last message repeated 1 times
[mjpeg @ 01240b80] bits 242 is invalid
[mjpeg @ 01240b80] No JPEG data found in image
[mjpeg @ 01240b80] bits 63 is invalid
[mjpeg @ 01240b80] dqt: invalid precision
[mjpeg @ 01240b80] bits 31 is invalid
[mjpeg @ 01240b80] Found EOI before any SOF, ignoring
[mjpeg @ 01240b80] No JPEG data found in image
[mjpeg @ 01240b80] Changing bps from 7 to 14
[mjpeg @ 01240b80] [IMGUTILS @ 0028f494] Picture size 36825x41166 is invalid
[mjpeg @ 01240b80] bits 61 is invalid
[mjpeg @ 01240b80] dqt: invalid precision
[mjpeg @ 01240b80] bits 253 is invalid
[mjpeg @ 01240b80] bits 45 is invalid
[mjpeg @ 01240b80] bits 232 is invalid
[image2 @ 0123f400] decoding for stream 0 failed
[image2 @ 0123f400] Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown), lossless): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, image2, from 'IMG1\%d.jpg':
  Duration: 00:00:02.44, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: mjpeg, none(bt470bg/unknown/unknown), lossless, 25 fps, 25 tbr, 25 tbn, 25 tbc
[buffer @ 03a61760] Unable to parse option value "0x0" as image size
[buffer @ 03a61760] Unable to parse option value "-1" as pixel format
[buffer @ 03a61760] Unable to parse option value "0x0" as image size
[buffer @ 03a61760] Error setting option video_size to value 0x0.
[graph 0 input from stream 0:0 @ 039574e0] Error applying options to the filter.
Error opening filters!

**Pull request closed without merging**
