### PR TITLE
GH-884: Time Series analysis support

### PR DESCRIPTION
**Pull request by AlexJCross**
Hi @cesarsouza ,

Adding exponentially weighted moving average calcs which relates to #884. These numbers have been tested against Python's pandas package and unit tests are in place for all the numbers. This PR provides functionality for exponentially weighted means, variance and covariance.

```python
from pandas import DataFrame

df = pd.DataFrame({'A' : [1, 3, 5, 6, 4, 2, 7, 8, 9, 2, 3, 4, 5, 6, 7],
                   'B' : [5, 3, 8, 6, 4, 4, 3, 8, 9, 0, 9, 9, 1, 9, 2]})

alpha = 0.5
df.ewm(adjust = True, alpha=alpha).mean()[df.index == 14]
df.ewm(adjust=True, alpha=alpha).cov(bias=True)[14]
```
I've added unit tests in the class `MeasuresTest`. Any questions/comments/critique very welcome.

Thanks,
Alex

### CODE REVIEW

**Comment by cesarsouza** [comment]
Wow Alex that's just amazing.

**Comment by cesarsouza** [comment]
Just to confirm, in the case of matrices, the weights go decreasing together with the rows, with the same weight being applied to all elements of the same row, is it correct?

**Comment by AlexJCross** [comment]
Yep - that's correct. It's very similar to Matlab‘s `ewstats` in that regard.

**Comment by AlexJCross** [comment]
Would you mind doing me a favour and confirming that I set up the documentation examples correctly? I've done it once before but I feel like a [cargo cult programmer](https://en.m.wikipedia.org/wiki/Cargo_cult_programming) every time I add anything (because I haven't worked out how to test sandcastle :( ). 

Thanks v much!

**Comment by cesarsouza** [comment]
Yep, the documentation examples seem to have been set up correctly, but I have to say that we will only know for sure whether everything is alright when I finally start compiling the documentation with Sandcastle. The problem is that it can take several hours to compile the documentation, so I only do it when we are approaching a release. And very often there are issues, but they are all easy to fix, so don't worry about that!

PS: Whenever I have to write a new ```<code source= ... >``` tag, I actually have to look up an existing one in a nearby class and use it as a base, because I can never remember exactly at which directory the path to the unit test is supposed to start!

**Comment by cesarsouza** [comment]
By the way, talking about a release - I feel that we should do another one really soon. There are way too many issues that have been fixed already! :-)

**Comment by AlexJCross** [comment]
Ok cool. If there's any problems with the documentation from my contributions let me know and I will try to fix!

**Comment by cesarsouza** [comment]
Ops! Actually was a small issue with the documentation that I only realized now once I tried to compile in release mode. In the first ExponentialWeightedMean method for example, there was documentation for a parameter "matrix", but the method had a parameter named "values" instead. Those errors can be captured by attempting to build the project in release mode (i.e. setting the configuration target to net462) which will enable documentation generation. 

By the way, if you would like, you can also download an extension called [GhostDoc](https://submain.com/download/ghostdoc/community/) that can write lots of boilerplate code for you. You can hit Ctrl+D or add the "///" lines on top of the method in VS and it will generate a starting text with all the parameters already named and "pseudo" documented. It is not perfect, but gives a good start!

**Comment by AlexJCross** [comment]
Ah ok. Sorry about that and thanks a lot for fixing. I am so used to Resharper (which automatically does all this kind of thing) I am a bit lost without it on my home laptop. Nice tips - I'll use Ghost doc and check release compile going forwards.

**Pull request merged**
