### PR TITLE
correction of typo errors in Sources/Accord.Video.DirectShow/VideoCap…

### PR DESCRIPTION
**Pull request by michel-carbone**
…tureDevice.cs

### CODE REVIEW

**Comment by michel-carbone** [comment]
tried to sign the CLA but get only a message "Hey, {{ user.value.login }}!"

**Comment by michel-carbone** [comment]
OK it finally worked by following these instructions https://github.com/cla-assistant/cla-assistant/issues/186

**Comment by fdncred** [comment]
conflicts

**Comment by michel-carbone** [comment]
> 
> 
> conflicts

hum there was no conflicts at the time of my commit (september 2018)... sorry... but the typo errors are still present in the current release of the file. If I get time one day i'll push again a commit for those corrections

cheers

**Comment by fdncred** [comment]
You are correct. Thanks.

**Pull request closed without merging**
