### PR TITLE
Updated DebugVisualizers to support Visual Studio 2017

### PR DESCRIPTION
**Pull request by fdncred**
And work with Accord Framework versus AForge.

### CODE REVIEW

**Comment by cesarsouza** [comment]
Hi @fdncred,

Thanks a lot for the contribution!

Do you happen to know if there is any way to automatically install debug visualizers through NuGet? I think those visualizers are a quite hidden feature right now. I guess almost no one realizes they even exist. 

I was wondering if there was anything we could do to make them easier to distribute and install.

Regards,
Cesar

**Comment by fdncred** [comment]
I'm not sure about NuGet but they can be distributed via Microsoft's "Extensions and Updates" which I believe points to their [marketplace](https://marketplace.visualstudio.com/search?term=Visualizers&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance).

Apparently this is [something](http://nugetmusthaves.com/Tag/Visualizers) you can do because Visualizers show up here.  Not sure how to do it. I just did a quick search.

I also updated the csproj with a post build action to copy the Visualizer to the proper folder, assuming they installed Visual Studio 2017 in it's default folder.

I wanted to get these changes in, just so it compiles and is usable. However, I'd like to make a bunch of changes, time permitting. So hopefully this is a good starting point.

**Comment by cesarsouza** [comment]
Absolutely. 

I was thinking about making a small change on them already, namely, to rename the "AForge" prefix in the namespace names to "Accord". But if you have more changes in mind, and it isn't much work for you, maybe you could try doing those changes on your side as well before you commit the next changes?

Regards,
Cesar

**Comment by fdncred** [comment]
Ok, No problem.  Do you want to accept and integrate this PR now, or should I work on making all the changes I was thinking about?  I just wanted to get something in that people could use first.

**Pull request merged**
