### PR TITLE
Pull opt parallel

### PR DESCRIPTION
**Pull request by fxbit**
Speed optimizations in KMean and SVM.
This optimizations are for .net 4.0 and up.

### CODE REVIEW

**Comment by cesarsouza** [comment]
Thank you very much for the pull request!

However, please, before I accept it, can I ask if you have actually noticed whether there was a significant speedup after those changes? I am just asking because I myself had decided not to paralelize those sections because those sections are likely to be used in parallel inside other methods who might already have been paralelized (such as multi-class learning). In this case, I thought the extra paralelization constructs would actually hurt the performance rather than improve it. But I may have been wrong, so please let me know!

In any case, thank you very much for the pull request, it has been much appreciated!

Best regards,
Cesar

**Comment by fxbit** [comment]
For the first commit we have see significant speedup in the learning phase of SVM.

In the second case that we have needed a KMean to run in samples of ~200K points and 128 clusters we have see significant speed-up in computations. In the KMean the PerformClustering part was using ParallelFor but not the starting randomization.

I have see that you are not using any unsafe/fixed code, have you try any or for portability reasons you have avoid it ?
In the past i have see a significant increase in the performance when i have modify code from safe to unsafe. 

BR,
Petros

**Comment by cesarsouza** [comment]
Thanks. I will accept the patches after I finish some modifications that I am about to commit in the development branch. Regarding the use of unsafe, I only use it in some particular contexts, mainly when I am working with images and multidimensional matrices. From my experience, they are not really necessary when handling jagged matrices and vectors.

Thank you again for the contribution!

Best regards,
Cesar

**Comment by anders9ustafsson** [comment]
@fxbit Have you verified the performance gain of the parallelization on several problems and hardware configurations? Admittedly, I have not benchmarked this particular code, but in general my personal experience is that you need to have quite large and time-consuming chunks for .NET parallelization to be beneficial. What is your opinion on Cesar's statement, that these sections are likely to be used in outer methods that are themselves parallelized?

Regards,
Anders @ Cureos

**Comment by fdncred** [comment]
conflicts

**Pull request closed without merging**
