### PR TITLE
Adding a range search method for KDTree

### PR DESCRIPTION
**Pull request by hzawary**
Hi dear Dr,

I've investigating about range search using Kd-Tree, since doesn't exist in Accord.Collections.KDTree class. Finally I implements an extension range search 2D for it. But I'm not sure about performance, complexity and the best algorithm or method.

```
        public static void KdTreeRangeQueryDemo()
        {
            // This is the same example found in Wikipedia page on
            // k-d trees: http://en.wikipedia.org/wiki/K-d_tree

            var image = UnmanagedImage.Create(800, 600, PixelFormat.Format24bppRgb);

            var rnd = new Random();

            // Suppose we have the following set of points:

            var points = new double[300000][];
            var listPoints = new List<IntPoint>(points.Length);
            for (int i = 0; i < points.Length; i++)
            {
                var point = new IntPoint(rnd.Next(0, image.Width), rnd.Next(0, image.Height));

                points[i] = new double[] { point.X, point.Y };

                listPoints.Add(point);
            }

            var region = new Rectangle(676, 441, 70, 55);

            new PointsMarker(listPoints, Color.DodgerBlue, 1).ApplyInPlace(image);
            new RectanglesMarker(region) { MarkerColor = Color.GreenYellow }.ApplyInPlace(image);

            var sw1 = new Stopwatch();
            sw1.Restart();
            var query1 = listPoints.FindAll((obj) =>
            {
                return
                obj.X > region.Left && obj.X < region.Right &&
                obj.Y > region.Top && obj.Y < region.Bottom;
            });
            sw1.Stop();

            listPoints.Clear();

            var sw2 = new Stopwatch();
            sw2.Restart();
            // To create a tree from a set of points, we use
            var tree = KDTree.FromData<int>(points, new Accord.Math.Distances.Manhattan(), true);
            sw2.Stop();

            var sw3 = new Stopwatch();
            sw3.Restart();
            var query2 = tree.Root.QueryKDTree2D(region);
            sw3.Stop();

            listPoints.AddRange(query2);

            var title = $"Create KDTree: {sw2.ElapsedMilliseconds}ms, Query KDTree: {sw3.ElapsedMilliseconds}ms, FindAll: {sw1.ElapsedMilliseconds}ms for {points.Length} random points.";
            new PointsMarker(query2 /*query1*/, Color.Tomato, 1).ApplyInPlace(image);

            ImageBox.Show(title, image, System.Windows.Forms.PictureBoxSizeMode.AutoSize);
        }

        public static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region)
        {
            return node.QueryKDTree2D(region, region);
        }

        private static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region, Rectangle subRegion)
        {
            var result = new List<IntPoint>();

            if (node != null && region.IntersectsWith(subRegion))
            {
                //if (node.Position.Length != 2)
                //    new DimensionMismatchException("node", "The node should have a 2D vector.");

                var point = new IntPoint((int)node.Position[0], (int)node.Position[1]);

                if (point.X > region.Left && point.X < region.Right &&
                    point.Y > region.Top && point.Y < region.Bottom)
                    result.Add(point);

                result.AddRange(node.Left.QueryKDTree2D(region, LeftRect(ref subRegion, ref node)));
                result.AddRange(node.Right.QueryKDTree2D(region, RightRect(ref subRegion, ref node)));
            }

            return result;
        }
        // helper: get the left rectangle of node inside parent's rect
        private static Rectangle LeftRect(ref Rectangle rect, ref KDTreeNode<int> node)
        {
            return node.Axis != 0 ?
                Rectangle.FromLTRB(rect.Left, rect.Top, rect.Right, (int)node.Position[1]) :
                Rectangle.FromLTRB(rect.Left, rect.Top, (int)node.Position[0], rect.Bottom);
        }
        // helper: get the right rectangle of node inside parent's rect
        private static Rectangle RightRect(ref Rectangle rect, ref KDTreeNode<int> node)
        {
            return node.Axis != 0 ?
                Rectangle.FromLTRB(rect.Left, (int)node.Position[1], rect.Right, rect.Bottom) :
                Rectangle.FromLTRB((int)node.Position[0], rect.Top, rect.Right, rect.Bottom);
        }
```
The result of above codes:
kdtreequeryextension

See the codes if necessary this functionality for adding to Accord.NET framework. Also it's be excellent if support more than 2D.

Regards,
H.Zawary

### CODE REVIEW

**Comment by cesarsouza** [comment]
Hi @hzawary, 

Wow, thanks a lot, this feature also looks amazing. I am trying to review it, but as you might have seen, there was a problem with the pull request - I think that the base version from which you started your code was way behind in comparison to the current development branch. As such, it is quite difficult to even review the changes that have been made.

Do you think you could re-submit the pull request, but starting from the most current version of Accord?

Again thanks a lot for the contribution!

Regards,
Cesar

**Comment by hzawary** [comment]
Oh! Yep :) but it's better for issue or pull request?!

**Comment by cesarsouza** [comment]
I think there are two ways this can be fixed, one of them is by rebasing your current branch to the latest version of Accord (I think you might need to do something like this: https://stackoverflow.com/questions/7929369/how-to-rebase-local-branch-with-remote-master) and re-committing. You wouldn't need to submit a new pull request, I think it would update automatically.

However, if this doesn't work or if it proves too difficult to do (I also forget the proper ways to do it all the time...) please also feel free to submit a new pull request after you have synced to the latest version, and we can just close this one later.

Lastly, if none of this works, I think I can also solve it on my side. However, it will take some time until I can finally dedicate some time to do it :-(

**Comment by hzawary** [comment]
Thanks for your consideration. Because the codes on the fly, I discard this pull-request and plan it as an issue and you can find the proper location of codes in the Accord framework for insert and improve it.
What do you think?!

**Comment by cesarsouza** [comment]
Hi @hzawary, I think this can work, just please let me know exactly what files you have modified and I can try to compare them against the current sources as well, just in case.

Thanks again!

Regards
Cesar

**Comment by hzawary** [comment]
Just 4 static functions is implement for KD Tree expansion class and doesn't modified any files.

`public static void KdTreeRangeQueryDemo()`: **For show how usage of them.**

`public static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region)`: **An extension for KDTreeNodes.**

`private static IList<IntPoint> QueryKDTree2D(this KDTreeNode<int> node, Rectangle region, Rectangle subRegion)`: **An recursive function in private.**

**// helper: get the right rectangle of node inside parent's rect**
`private static Rectangle LeftRect(ref Rectangle rect, ref KDTreeNode<int> node)`

**// helper: get the right rectangle of node inside parent's rect**
`private static Rectangle RightRect(ref Rectangle rect, ref KDTreeNode<int> node)`

**Pull request closed without merging**
